# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usAp6v8N09gkjDYTztiVreXWm4Zogt90
"""

from google.colab import drive
drive.mount('/content/drive')

ls

pip install ultralytics

from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO("yolov8n-seg.pt")

# Run inference on the source
results = model("argoverse.mp4", save=True, classes=2) # list of Results objects